Implement requesting CSRs and submitting certs on pony
mit-scripts/scripts-pony pull request #3
Opened 2017-07-28 14:28 UTC by jakob223

Add a page on pony where users can request CSRs and then submit the certs they get, which are automatically verified and placed in LDAP. This finishes https://scripts.mit.edu/trac/ticket/241

2017-07-28 14:29 UTC, jakob223 commented
Is there a way to deploy this somewhere as the pony user to test it before running it on main pony?

2017-08-11 00:28 UTC, andersk requested changes

2017-08-11 00:28 UTC, andersk commented on scriptspony/templates/index.mak
> +                  <td><span class="secure-btn-disabled"><span class="fa fa-lock"></span></span></td>
Domains with certificates may still need CSRs for renewal purposes.

2017-08-11 00:28 UTC, andersk commented on verify-certs/verify.go
> +package main
Without a compelling reason, I’d strongly prefer to keep everything in Python. What is this checking that vhostcert doesn’t?

2017-08-11 00:28 UTC, andersk commented on verify-certs/verify.go
> +	return errors.New("certificate chain as presented is out of order")
No need for this. vhostcert already reorders the certs correctly, which is much friendlier.

2017-08-11 00:28 UTC, andersk commented on scriptspony/controllers/root.py
> +                    # TODO: move this somewhere scripts-ey. Source is in this repo.
Obviously that’s going to need to be addressed one way or another.

2017-08-11 00:28 UTC, andersk commented on scriptspony/templates/index.mak
> +                  <td><span class="edit-btn-disabled"><span class="fa fa-ban"></span></span></td>
This should link to the FAQ rather than suggesting that certificates on mit.edu are impossible.

2017-08-11 00:28 UTC, andersk commented on scriptspony/templates/request_cert.mak
> +Choose which aliases to include:<br><ul>
This is XHTML, `<br>` must be `<br />`. Please run this through validator.w3.org; there are many other errors.

2017-08-11 00:28 UTC, andersk commented on scriptspony/vhosts.py
> +# CSRs and install certs for .mit.edu domains?
Yes.

2017-08-11 00:28 UTC, andersk commented on scriptspony/vhosts.py
> +    pass
I think you meant to delete this?

2017-08-11 00:28 UTC, andersk commented on scriptspony/config/environment.py
> +    url = ('mysql://sql.mit.edu/%s+scripts-pony?read_default_file=~/.sql/my.cnf'
What happened here?

2017-08-11 17:18 UTC, jakob223 commented on scriptspony/config/environment.py
> +    url = ('mysql://sql.mit.edu/%s+scripts-pony?read_default_file=~/.sql/my.cnf'
I'm not entirely sure why, but I believed that ~/.my.cnf didn't have the right information in my locker, then I accidentally committed the change. Will revert.

2017-08-11 17:30 UTC, jakob223 commented on scriptspony/config/environment.py
> +    url = ('mysql://sql.mit.edu/%s+scripts-pony?read_default_file=~/.sql/my.cnf'
ah, daemon.scripts didn't have any permissions for `/mit/jakobw`

2017-08-12 21:54 UTC, jakob223 commented on scriptspony/templates/index.mak
> +                  <td><span class="secure-btn-disabled"><span class="fa fa-lock"></span></span></td>
I think my solution to this is inelegant - thoughts?

2017-08-12 22:04 UTC, jakob223 commented on verify-certs/verify.go
> +package main
The validity of the passed certificate chain - that a certificate hasn't expired, that the certificates are actually valid, that it's signed by a trusted root CA. 

All `vhostcert` checks is that there's a chain of certs that is orderable in that each claims to be issued by the next.

2017-08-12 22:11 UTC, jakob223 commented on verify-certs/verify.go
> +package main
I find the python stuff for dealing with certificates to be pretty icky, so I wrote this in go.

2017-08-12 22:13 UTC, jakob223 commented on scriptspony/templates/request_cert.mak
> +Choose which aliases to include:<br><ul>
I fixed that and a bunch of other things. The validator is still complaining about the `form` and `placeholder` attributes on my textarea. What's the rationale for not allowing HTML5 features that won't detract from older browsers' experiences?

2017-08-12 22:13 UTC, aaazalea reviewed
I think I've addressed all the things. @andersk can you take a look at it?

Er, all the things except moving the go binary somewhere scripts-ey, if keeping it around is acceptable.

2017-11-25 05:53 UTC, jakob223 commented
bump @andersk can you look at this again?

2019-04-24 22:23 UTC, jakob223 commented
Closing this since it's been almost 2 years and it's not clear it's ever going to be reviewed.

2019-04-24 22:23 UTC, closed without merging